apiVersion: v1
kind: ServiceAccount
metadata:
  name: backup-operator-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: backup-operator-clusterrole
rules:

  # Framework: knowing which other operators are running (i.e. peering).
  - apiGroups: [kawaja.net]
    resources: [clusterkopfpeerings]
    verbs: [list, watch, patch, get]
  - apiGroups: [apiextensions.k8s.io]
    resources: [customresourcedefinitions]
    verbs: [list, get]

  # Application: read-only access for watching cluster-wide.
  - apiGroups: [kawaja.net]
    resources: ['*']
    verbs: [list, watch]
  - apiGroups: [""]
    resources: [pods]
    verbs: [list, get, watch, patch, update]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: backup-operator-role-default
rules:

  # Framework: knowing which other operators are running (i.e. peering).
  - apiGroups: [kawaja.net]
    resources: [kopfpeerings]
    verbs: [list, watch, patch, get]

  # Framework: posting the events about the handlers progress/errors.
  - apiGroups: [events.k8s.io]
    resources: [events]
    verbs: [create]
  - apiGroups: [""]
    resources: [events]
    verbs: [create]

  # Application: watching & handling for the custom resource we declare.
  - apiGroups: [kawaja.net]
    resources: ['*']
    verbs: [get, list, watch, patch]

  # Application: other resources it produces and manipulates.
  - apiGroups: [""]
    resources: [pods,pods/status]
    verbs: [create, get, patch, update, delete]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: backup-operator-clusterrole-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: backup-operator-clusterrole
subjects:
  - kind: ServiceAccount
    name: backup-operator-sa
    namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: default
  name: backup-operator-role-binding-default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: backup-operator-role-default
subjects:
  - kind: ServiceAccount
    name: backup-operator-sa
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backup-operator
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      application: backup-operator
  template:
    metadata:
      labels:
        application: backup-operator
    spec:
      serviceAccountName: backup-operator-sa
      containers:
      - name: backup-operator
        image: docker-registry.kawaja.net/backup-operator
      imagePullSecrets:
      - name: docker-registry-config
# vim: sw=2 et ts=2
