apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: backuptypes.kawaja.net
spec:
  scope: Namespaced
  group: kawaja.net
  names:
    kind: BackupType
    plural: backuptypes
    singular: backuptype
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              x-kubernetes-preserve-unknown-fields: true
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true
      additionalPrinterColumns:
        - name: Type
          type: string
          priority: 0
          jsonPath: .spec.type
          description: Execution type for this backup type.
        - name: Message
          type: string
          priority: 0
          jsonPath: .status.create.message
          description: As returned from the handler (sometimes).
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: backups.kawaja.net
spec:
  scope: Namespaced
  group: kawaja.net
  names:
    kind: Backup
    plural: backups
    singular: backup
    shortNames:
      - bu
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              x-kubernetes-preserve-unknown-fields: true
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true
      additionalPrinterColumns:
        - name: LastRun
          type: date
          priority: 0
          jsonPath: .status.backup.last_run
          description: Time of most recent backup attempt.
        - name: Loops
          type: integer
          jsonPath: .status.backup.loops
          description: Number of loops the daemon has processed.
        - name: State
          type: string
          priority: 0
          jsonPath: .status.state
          description: State of backup operator.
        - name: CurrentlyRunning
          type: string
          priority: 0
          jsonPath: .status.currently_running
          description: Name of backup which is currently running.
        - name: BackupPod
          type: string
          priority: 0
          jsonPath: .status.backup_pod
          description: Name of pod for the backup which is currently running.
        - name: Message
          type: string
          priority: 0
          jsonPath: .status.backup.message
          description: As returned from the handler (sometimes).
