apiVersion: kawaja.net/v1
kind: BackupType
metadata:
  name: backuptest
spec:
  type: pod
  podspec:
    containers:
    - name: test
      image: busybox
      command: ["sh", "-x", "-c"]
      args:
      - |
        echo "FIELD=$FIELD"
        sleep 10
        exit 0
      env:
      - name: FIELD
        value: "{','.join(spec.get('backupItems', 'none'))}"
      resources:
        requests:
          memory: 200Mi
          cpu: 50m
      securityContext:
        privileged: true
        capabilities:
          add:
            - SYS_ADMIN
    restartPolicy: OnFailure
