name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: Generate Tag
      id: tag
      run: |
        echo "::set-output name=shortsha::$(echo ${GITHUB_SHA::7})"
        DATE=$(date +$Y%m%d%H%M%S)
        GD=$(git describe --tags || (git rev-parse HEAD | cut -c1-7))
        GDS=${GD%%-*}
        TAGS="${GD} ${GD}-${DATE}"
        if [ "${GD}" = "${GDS}" ]; then
          TAGS="${TAGS} ${GD%.*} ${GD%.*}-${DATE}"  # add vx.y tag if the current commit is directly tagged
        fi
        echo "::set-output name=imagetags::${TAGS}"
    - name: Build the Docker image
      run: |
        docker build oaatoperator --file build/Dockerfile --tag ${{github.repository}}
        for tag in ${{steps.tag.outputs.imagetags}}; do
          echo "tagging with $tag"
          docker tag ${{github.repository}} ${{github.repository}}:$tag
        done
