name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: Build the Docker image (with :<sha> and :dev tags)
      run: |
        CR=ghcr.io/${{github.repository}}
        docker build oaatoperator --file build/Dockerfile --tag ${CR}:${GITHUB_SHA::7}
        echo ${{ secrets.CR_PAT }} | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin
        docker tag ${CR}:${GITHUB_SHA::7} ${CR}:dev
        docker push ${CR}:${GITHUB_SHA::7}
        docker push ${CR}:dev
