name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Build the Docker image
      run: |
        docker build oaatoperator --file build/Dockerfile --tag ${GITHUB_SHA::7}
        echo ${{ secrets.CR_PAT }} | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin
        docker push ghcr.io/${{github.repository}}:${GITHUB_SHA::7}
