name: Release Docker Containers

on:
  push:
    tags: [ 'v*' ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Generate Tags
      id: tag
      run: |
        echo "::set-output name=shortsha::$(echo ${GITHUB_SHA::7})"
        GD=$(git describe --tags)
        GDS=${GD%%-*}
        if [ "${GD}" = "${GDS}" ]; then
          TAGS="${GD} latest ${GD%.*}"  # include vx.y.z, vx.y and latest
        else
          echo "git describe returned '${GD}' instead of a simple vx.y.z" >&2
          exit 1
        fi
        echo "TAGS: ${TAGS}"
        echo "::set-output name=imagetags::${TAGS}"
    - name: Login to Repo
      uses: docker/login-action@v2.2.0
      with:
        registry: ghcr.io
        username: $GITHUB_ACTOR
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Tag the Docker image
      run: |
        CR="ghcr.io/${{github.repository}}"
        docker pull ${CR}:${GITHUB_SHA::7}
        for tag in ${{steps.tag.outputs.imagetags}}; do
          echo "tagging with $tag"
          docker tag ${CR}:${GITHUB_SHA::7} ${CR}:$tag
          docker push ${CR}:$tag
        done
